version: '3.8'

services:
  db:
    image: postgres:13
    container_name: processos_db
    environment:
      POSTGRES_DB: processos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
