server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/processos_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      example: DEBUG
